<?php

// Data functions (insert, update, delete, form) for table snacks

// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function snacks_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('snacks');
	if(!$arrPerm['insert']) return false;

	$data = [
		'brand' => Request::val('brand', ''),
		'category' => Request::val('category', ''),
		'flavor' => Request::val('flavor', ''),
		'item' => Request::val('item', ''),
		'Illustration' => Request::val('Illustration', ''),
		'serving_size' => Request::val('serving_size', ''),
		'calories' => Request::val('calories', ''),
		'fat' => Request::val('fat', ''),
		'carbs' => Request::val('carbs', ''),
		'protein' => Request::val('protein', ''),
		'fiber' => Request::val('fiber', ''),
		'sodium' => Request::val('sodium', ''),
		'am_link' => Request::val('am_link', ''),
		'name' => Request::val('name', ''),
		'rating' => Request::val('rating', ''),
		'starcount' => Request::val('starcount', ''),
	];


	// hook: snacks_before_insert
	if(function_exists('snacks_before_insert')) {
		$args = [];
		if(!snacks_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('snacks', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('snacks', $recID, calculated_fields()['snacks']);

	// hook: snacks_after_insert
	if(function_exists('snacks_after_insert')) {
		$res = sql("SELECT * FROM `snacks` WHERE `ID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!snacks_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('snacks', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) snacks_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function snacks_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function snacks_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('snacks', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: snacks_before_delete
	if(function_exists('snacks_before_delete')) {
		$args = [];
		if(!snacks_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `snacks` WHERE `ID`='{$selected_id}'", $eo);

	// hook: snacks_after_delete
	if(function_exists('snacks_after_delete')) {
		$args = [];
		snacks_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='snacks' AND `pkValue`='{$selected_id}'", $eo);
}

function snacks_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('snacks', $selected_id, 'edit')) return false;

	$data = [
		'brand' => Request::val('brand', ''),
		'category' => Request::val('category', ''),
		'flavor' => Request::val('flavor', ''),
		'item' => Request::val('item', ''),
		'Illustration' => Request::val('Illustration', ''),
		'serving_size' => Request::val('serving_size', ''),
		'calories' => Request::val('calories', ''),
		'fat' => Request::val('fat', ''),
		'carbs' => Request::val('carbs', ''),
		'protein' => Request::val('protein', ''),
		'fiber' => Request::val('fiber', ''),
		'sodium' => Request::val('sodium', ''),
		'am_link' => Request::val('am_link', ''),
		'name' => Request::val('name', ''),
		'rating' => Request::val('rating', ''),
		'starcount' => Request::val('starcount', ''),
	];

	// get existing values
	$old_data = getRecord('snacks', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: snacks_before_update
	if(function_exists('snacks_before_update')) {
		$args = ['old_data' => $old_data];
		if(!snacks_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'snacks', 
		backtick_keys_once($set), 
		['`ID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="snacks_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('snacks', $data['selectedID'], calculated_fields()['snacks']);

	// hook: snacks_after_update
	if(function_exists('snacks_after_update')) {
		$res = sql("SELECT * FROM `snacks` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['ID'];
		$args = ['old_data' => $old_data];
		if(!snacks_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='snacks' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function snacks_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('snacks');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='snacks' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='snacks' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `snacks` WHERE `ID`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'snacks_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
	}

	// code for template based detail view forms

	// open the detail view template
	$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/snacks_templateDV.html';
	$templateCode = @file_get_contents($template_file);

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'ID details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return snacks_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return snacks_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return snacks_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#brand').replaceWith('<div class=\"form-control-static\" id=\"brand\">' + (jQuery('#brand').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#category').replaceWith('<div class=\"form-control-static\" id=\"category\">' + (jQuery('#category').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#flavor').replaceWith('<div class=\"form-control-static\" id=\"flavor\">' + (jQuery('#flavor').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#item').replaceWith('<div class=\"form-control-static\" id=\"item\">' + (jQuery('#item').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Illustration').replaceWith('<div class=\"form-control-static\" id=\"Illustration\">' + (jQuery('#Illustration').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#serving_size').replaceWith('<div class=\"form-control-static\" id=\"serving_size\">' + (jQuery('#serving_size').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#calories').replaceWith('<div class=\"form-control-static\" id=\"calories\">' + (jQuery('#calories').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#fat').replaceWith('<div class=\"form-control-static\" id=\"fat\">' + (jQuery('#fat').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#carbs').replaceWith('<div class=\"form-control-static\" id=\"carbs\">' + (jQuery('#carbs').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#protein').replaceWith('<div class=\"form-control-static\" id=\"protein\">' + (jQuery('#protein').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#fiber').replaceWith('<div class=\"form-control-static\" id=\"fiber\">' + (jQuery('#fiber').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#sodium').replaceWith('<div class=\"form-control-static\" id=\"sodium\">' + (jQuery('#sodium').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#am_link').replaceWith('<div class=\"form-control-static\" id=\"am_link\">' + (jQuery('#am_link').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#name').replaceWith('<div class=\"form-control-static\" id=\"name\">' + (jQuery('#name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#rating').replaceWith('<div class=\"form-control-static\" id=\"rating\">' + (jQuery('#rating').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#starcount').replaceWith('<div class=\"form-control-static\" id=\"starcount\">' + (jQuery('#starcount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(brand)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(category)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(flavor)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(item)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Illustration)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(serving_size)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(calories)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fat)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(carbs)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(protein)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fiber)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(sodium)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(am_link)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(rating)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(starcount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(favorite)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', safe_html($urow['ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', html_attr($row['ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(brand)%%>', safe_html($urow['brand']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(brand)%%>', html_attr($row['brand']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(brand)%%>', urlencode($urow['brand']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(category)%%>', safe_html($urow['category']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(category)%%>', html_attr($row['category']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(category)%%>', urlencode($urow['category']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(flavor)%%>', safe_html($urow['flavor']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(flavor)%%>', html_attr($row['flavor']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(flavor)%%>', urlencode($urow['flavor']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(item)%%>', safe_html($urow['item']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(item)%%>', html_attr($row['item']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(item)%%>', urlencode($urow['item']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Illustration)%%>', safe_html($urow['Illustration']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Illustration)%%>', html_attr($row['Illustration']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Illustration)%%>', urlencode($urow['Illustration']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(serving_size)%%>', safe_html($urow['serving_size']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(serving_size)%%>', html_attr($row['serving_size']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serving_size)%%>', urlencode($urow['serving_size']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(calories)%%>', safe_html($urow['calories']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(calories)%%>', html_attr($row['calories']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(calories)%%>', urlencode($urow['calories']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(fat)%%>', safe_html($urow['fat']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(fat)%%>', html_attr($row['fat']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fat)%%>', urlencode($urow['fat']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(carbs)%%>', safe_html($urow['carbs']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(carbs)%%>', html_attr($row['carbs']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(carbs)%%>', urlencode($urow['carbs']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(protein)%%>', safe_html($urow['protein']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(protein)%%>', html_attr($row['protein']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(protein)%%>', urlencode($urow['protein']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(fiber)%%>', safe_html($urow['fiber']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(fiber)%%>', html_attr($row['fiber']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fiber)%%>', urlencode($urow['fiber']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(sodium)%%>', safe_html($urow['sodium']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(sodium)%%>', html_attr($row['sodium']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sodium)%%>', urlencode($urow['sodium']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(am_link)%%>', safe_html($urow['am_link']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(am_link)%%>', html_attr($row['am_link']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(am_link)%%>', urlencode($urow['am_link']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', safe_html($urow['name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', html_attr($row['name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode($urow['name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(rating)%%>', safe_html($urow['rating']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(rating)%%>', html_attr($row['rating']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rating)%%>', urlencode($urow['rating']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(starcount)%%>', safe_html($urow['starcount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(starcount)%%>', html_attr($row['starcount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(starcount)%%>', urlencode($urow['starcount']), $templateCode);
		$templateCode = str_replace('<%%VALUE(favorite)%%>', safe_html($urow['favorite']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(favorite)%%>', urlencode($urow['favorite']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(brand)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(brand)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(category)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(category)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(flavor)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(flavor)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(item)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(item)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Illustration)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Illustration)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(serving_size)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serving_size)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(calories)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(calories)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fat)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fat)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(carbs)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(carbs)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(protein)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(protein)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fiber)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fiber)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(sodium)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sodium)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(am_link)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(am_link)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(rating)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(rating)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(starcount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(starcount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(favorite)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(favorite)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('snacks');
	if($selected_id) {
		$jdata = get_joined_record('snacks', $selected_id);
		if($jdata === false) $jdata = get_defaults('snacks');
		$rdata = $row;
	}
	$templateCode .= loadView('snacks-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: snacks_dv
	if(function_exists('snacks_dv')) {
		$args = [];
		snacks_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}