<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/snacks.php');
	include_once(__DIR__ . '/snacks_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('snacks');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'snacks';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`snacks`.`ID`" => "ID",
		"`snacks`.`brand`" => "brand",
		"`snacks`.`category`" => "category",
		"`snacks`.`flavor`" => "flavor",
		"`snacks`.`item`" => "item",
		"`snacks`.`Illustration`" => "Illustration",
		"`snacks`.`serving_size`" => "serving_size",
		"`snacks`.`calories`" => "calories",
		"`snacks`.`fat`" => "fat",
		"`snacks`.`carbs`" => "carbs",
		"`snacks`.`protein`" => "protein",
		"`snacks`.`fiber`" => "fiber",
		"`snacks`.`sodium`" => "sodium",
		"`snacks`.`am_link`" => "am_link",
		"`snacks`.`name`" => "name",
		"`snacks`.`rating`" => "rating",
		"`snacks`.`starcount`" => "starcount",
		"`snacks`.`favorite`" => "favorite",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`snacks`.`ID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => '`snacks`.`rating`',
		17 => '`snacks`.`starcount`',
		18 => '`snacks`.`favorite`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`snacks`.`ID`" => "ID",
		"`snacks`.`brand`" => "brand",
		"`snacks`.`category`" => "category",
		"`snacks`.`flavor`" => "flavor",
		"`snacks`.`item`" => "item",
		"`snacks`.`Illustration`" => "Illustration",
		"`snacks`.`serving_size`" => "serving_size",
		"`snacks`.`calories`" => "calories",
		"`snacks`.`fat`" => "fat",
		"`snacks`.`carbs`" => "carbs",
		"`snacks`.`protein`" => "protein",
		"`snacks`.`fiber`" => "fiber",
		"`snacks`.`sodium`" => "sodium",
		"`snacks`.`am_link`" => "am_link",
		"`snacks`.`name`" => "name",
		"`snacks`.`rating`" => "rating",
		"`snacks`.`starcount`" => "starcount",
		"`snacks`.`favorite`" => "favorite",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`snacks`.`ID`" => "ID",
		"`snacks`.`brand`" => "Brand",
		"`snacks`.`category`" => "Category",
		"`snacks`.`flavor`" => "Flavor",
		"`snacks`.`item`" => "Item",
		"`snacks`.`Illustration`" => "Illustration",
		"`snacks`.`serving_size`" => "Serving size",
		"`snacks`.`calories`" => "Calories",
		"`snacks`.`fat`" => "Fat",
		"`snacks`.`carbs`" => "Carbs",
		"`snacks`.`protein`" => "Protein",
		"`snacks`.`fiber`" => "Fiber",
		"`snacks`.`sodium`" => "Sodium",
		"`snacks`.`am_link`" => "Am link",
		"`snacks`.`name`" => "Name",
		"`snacks`.`rating`" => "Avgstar",
		"`snacks`.`starcount`" => "Starcount",
		"`snacks`.`favorite`" => "Favorite",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`snacks`.`ID`" => "ID",
		"`snacks`.`brand`" => "brand",
		"`snacks`.`category`" => "category",
		"`snacks`.`flavor`" => "flavor",
		"`snacks`.`item`" => "item",
		"`snacks`.`Illustration`" => "Illustration",
		"`snacks`.`serving_size`" => "serving_size",
		"`snacks`.`calories`" => "calories",
		"`snacks`.`fat`" => "fat",
		"`snacks`.`carbs`" => "carbs",
		"`snacks`.`protein`" => "protein",
		"`snacks`.`fiber`" => "fiber",
		"`snacks`.`sodium`" => "sodium",
		"`snacks`.`am_link`" => "am_link",
		"`snacks`.`name`" => "name",
		"`snacks`.`rating`" => "rating",
		"`snacks`.`starcount`" => "starcount",
		"`snacks`.`favorite`" => "favorite",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`snacks` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 0;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = (getLoggedAdmin() !== false);
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = (getLoggedAdmin() !== false);
	$x->AllowNavigation = 1;
	$x->AllowPrinting = (getLoggedAdmin() !== false);
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 0;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'snacks_view.php';
	$x->RedirectAfterInsert = 'snacks_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Pronacks';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`snacks`.`ID`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Brand', 'Category', 'Flavor', 'Item', 'Illustration', 'Serving size', 'Calories', 'Fat', 'Carbs', 'Protein', 'Fiber', 'Sodium', 'Am link', 'Name', 'Avgstar', 'Starcount', 'Favorite', ];
	$x->ColFieldName = ['brand', 'category', 'flavor', 'item', 'Illustration', 'serving_size', 'calories', 'fat', 'carbs', 'protein', 'fiber', 'sodium', 'am_link', 'name', 'rating', 'starcount', 'favorite', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/snacks_templateTV.html';
	$x->SelectedTemplate = 'templates/snacks_templateTVS.html';
	$x->TemplateDV = 'templates/snacks_templateDV.html';
	$x->TemplateDVP = 'templates/snacks_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: snacks_init
	$render = true;
	if(function_exists('snacks_init')) {
		$args = [];
		$render = snacks_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: snacks_header
	$headerCode = '';
	if(function_exists('snacks_header')) {
		$args = [];
		$headerCode = snacks_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: snacks_footer
	$footerCode = '';
	if(function_exists('snacks_footer')) {
		$args = [];
		$footerCode = snacks_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
